# Dummy code to trigger build
language: node_js
node_js:
- node

deploy:
  provider: s3
  access_key_id: AKIAIYGY7HGYND6VF6XA
  secret_access_key:
    secure: eReBRlQnKUT+WoVbdTYgPf7b7b/9Yt5+WKgRw4bWf0FJZcyk0QiI1wLTncp1PHP7QYZclEp1qJB39e/OSRt+SsGQsoWG1g2dm87L58REtZwKHRFFY9pNnztaqnNvffZ+OudU9BMr7oaXBWyWV6y7hP8ng5ko/jbEDwEEBTVadY9KFu9O2SeOKALTVRLzY3HoxfNF/lQN1S6j51KmNsWZQSyvgbs7S01FKsDLbnK2UfjVoaYuq6MyswnVLjUd+cUP8Sm1mZvkKqSH9awiengIrX9RxVeuJ2ODwPX4O639Ok2eISLmaDYMNRy6XSH++3rrmWAy3hx+IbDL1UnK/gdiFbLH9iFsKMTR4YfaauGleYgtEQUfVxESqd9/MnIlg60P3Ihq72gXQkTa+Sf59GkeSIuX4oe3cyIzeidjM7onIEV6DlsWjwoJIVZw4qDWE6J3Duk6HvIWQTMOJK71BoPQMNQWSFV8qj54ikCMj/wfOO9fBThqwBW55BRgh5XqffpaLKvqRWm55m4tUlPgO/4Bt9VV+jry7Z45Nyct/3HL//umnH7W8GTY0P8jDiATsIr30E7vLFGs+1MqUwEJPIagEIchojI+Xhj62qHm7d7m7jM1V4Gbsj7Rz4TEhgy0Vd0DaEkXKSVETow2dmpBt3fDVCNcRg7fI2+r3sLIOBjjg2U=
  bucket: r18-livedash
  skip_cleanup: true
  on:
    repo: RevolveNTNU/R18_LiveDashClient
    branch: dev
