# Dummy code to trigger build
language: node_js
install:
  - npm -v
deploy:
  provider: s3
  access_key_id: AKIAIYGY7HGYND6VF6XA
  secret_access_key:
    secure: FyEk4BPaRFE2CPQiZDisn1ZxzMzJeJ6c9FWu/EHKuehEmJIIDiE9KrGmxtQHCxoXRGuIyweb2z01TDBCayX0HGusPTHLTpFE88wdQlDaxr9mLBzSOIT7zf1AVQgQFi7XxQ6MVjxANaAw6I6upaHnuQEXXhb+zNa8uIpxTC1WcRK0xPCcn08e9qY22GebBsCBb8iR1ZdSL/GIVrQ1J4IPGXZ5687on18pIkcuvusPRGf/rw3xzThNrdinC0GQQiFBCNHpg+AdaJYzAdSSOUgfrF1uqyZwBrbinTaKOTIo7UECvT5KrPMQLptWXIfuT5somT9txMRPJ13IBOxmpEwcIXjCKa9HF9tDLmGD7h5rXikcmzBdi5a49aahkxcSxJxuctrgrSMZ9QE9QpJJFtgsIGCyjptIcEOfHkGhzbbX33MvWIlhtRm0ejZYIKvRvOLy+tC5AzRA8ILTuu9GOS7lNEJoK/b85+pA9bA4DbKB29T14ZE7wMfSQmsLoPG498YgZKN+KgP9+8h+0FaR/Zz4eAuf0AxyefwbdZNAUIDuIhO4ektPp6t1UXTJMUKGesym9ZSboG4/HlNrZNWKmLMC6jH5QaSu658mHMsizgZUc1ZywdWAbhTKJBK5V8ogpxFD3VH03S/n4W6d3XdtbRYQ12zfxApunX3ts91iGoIuhPs=
  bucket: r18-livedash
  skip_cleanup: true