# Dummy code to trigger build
language: node_js
node_js:
- node

deploy:
  provider: s3
  access_key_id: AKIAIYGY7HGYND6VF6XA
  secret_access_key:
    secure: kzEdHbkust8tKQCrcHO2WoJ8JhSjSpxCYJlAbCum4p7qFYarhGysz/LvX2+d4e2nuJbMq2aQ/bd9HXRZ7yMonyMJhAtofNW3trA57Njew3gyLGsRUfVMB7ePinh3YVsODB7AFQ9XR1kQm7IdCdIaz5aNN1G2UfwcJr6S+aCMvS7Kvd3tieYhTN+++doHv0GtC43dGy9dslu6J9C7qzWsc+SNW7wC5DL1AxoZpk1HbDXe5aSIig8qUmmS4bL0dclVxP/ufOHTbsbR47aCVU1CcRJXU8OmZJC/KG2eVciJfCJFcWIGSfFtMWe3jgj4qEub6HDyd4J63a6/7cQFzSdWk2w85DDRRx4UuELirIw/UYlsQ3e6pbNiFKgW7WVSiU7kLdE5CJBQ8Qcc6iURPKtX/R8+PRHg06hlF5VDp01E30QgeoKmkeExZtzV512e7NxI3v/NRWX9hYaELl2sXA1Lig1D6uDRWmRX/xGQnk3Xu/e4i9ykq+Sn8ckNHu7XiLcuhCyUaUrunH47lEzeVALuYTXG9MZCIYT68Pk6coF8jf7ahz99kmI8nogHP/WOTTW4qr74FZJeUFHh17O5RCmV2cKM9IAX2NgP21q/+0teKfNUsDFzc+0uSMvb4fO+1CY6MiQcmwyAES2SKyqnwZ1BBI5fAg/pFHVhMN+7nT3LPdk=
  bucket: r18-livedash
  on:
    repo: RevolveNTNU/R18_LiveDashClient
    branch: master
    
notifications:
  email: false
